//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReSearch.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public int BookTitleID { get; set; }
        public string CheckOutPatronID { get; set; }
        public bool IsCheckedOut { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual BookTitle BookTitle { get; set; }
    }
}
