//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReSearch.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTitle
    {
        public BookTitle()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int BookTitleID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int SubCategoryID { get; set; }
        public string ShelfLocation { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
