//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    public int BookID { get; set; }
    public int BookTitleID { get; set; }
    public string CheckOutPatronID { get; set; }
    public bool IsCheckedOut { get; set; }
    public Nullable<System.DateTime> PickUpDate { get; set; }
    public Nullable<System.DateTime> ReturnDate { get; set; }

    public virtual BookTitle BookTitle { get; set; }
}

public partial class BookTitle
{
    public BookTitle()
    {
        this.Books = new HashSet<Book>();
    }

    public int BookTitleID { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public int SubCategoryID { get; set; }
    public string ShelfLocation { get; set; }

    public virtual ICollection<Book> Books { get; set; }
    public virtual SubCategory SubCategory { get; set; }
}

public partial class Category
{
    public Category()
    {
        this.SubCategories = new HashSet<SubCategory>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<SubCategory> SubCategories { get; set; }
}

public partial class SubCategory
{
    public SubCategory()
    {
        this.BookTitles = new HashSet<BookTitle>();
    }

    public int SubCategoryID { get; set; }
    public string SubCategoryName { get; set; }
    public int CategoryID { get; set; }
    public string SubCategorySynonyms { get; set; }

    public virtual ICollection<BookTitle> BookTitles { get; set; }
    public virtual Category Category { get; set; }
}

public partial class sp_SearchBooks_Result
{
    public string Title { get; set; }
    public string Author { get; set; }
    public string Category { get; set; }
    public string SubCategory { get; set; }
}
