<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeBehind="Patrons.aspx.cs" Inherits="BookReSearch.Admin.Patrons" %>
<asp:Content ID="Content1" ContentPlaceHolderID="AdminContent" runat="server">
    <h3>Manage Patrons</h3>
    <asp:GridView ID="gvPatrons" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False" DataKeyNames="UserName" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
        <Columns>
            <asp:BoundField DataField="UserName" HeaderText="UserName" ReadOnly="True" />
            <asp:TemplateField SortExpression="FirstName" HeaderText="First Name">
                <ItemTemplate><%# Eval("FirstName") %></ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="FirstName" runat="server" Text='<%# Bind("FirstName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="LastName" HeaderText="Last Name">
                <ItemTemplate><%# Eval("LastName") %></ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="LastName" runat="server" Text='<%# Bind("LastName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField SortExpression="Phone" HeaderText="Phone Number">
                <ItemTemplate><%# Eval("Phone") %></ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="Phone" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
